name: CI/CD POC Workflow

on:
  push:
    branches:
      - dev
      - UAT
      - main

jobs:
  build_aab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build AAB
        run: |
          echo "Job 1: Building AAB for branch '${{ github.event.ref }}'"

  shield_aab:
    runs-on: ubuntu-latest
    needs: build_aab
    if: github.event.ref == 'refs/heads/UAT' || github.event.ref == 'refs/heads/main'
    steps:
      - name: Shield AAB
        run: |
          echo "Job 2: Shielding AAB for branch '${{ github.event.ref }}'"

  deploy_aab:
    runs-on: ubuntu-latest
    needs: shield_aab
    if: github.event.ref == 'refs/heads/UAT' || github.event.ref == 'refs/heads/main'
    steps:
      - name: Deploy AAB
        run: |
          echo "Job 3: Deploying AAB for branch '${{ github.event.ref }}'"

  release_to_github_dev:
    runs-on: ubuntu-latest
    needs: build_aab
    if: github.event.ref == 'refs/heads/dev'
    steps:
      - name: Release to GitHub
        run: |
          echo "Job 4: Releasing Dev AAB..."

  release_to_github_uat_main:
    runs-on: ubuntu-latest
    needs: deploy_aab
    if: github.event.ref == 'refs/heads/UAT' || github.event.ref == 'refs/heads/main'
    steps:
      - name: Release to GitHub
        run: |
          echo "Job 4: Releasing UAT/Main AAB..."
