name: CI/CD POC Workflow

on:
  push:
    branches:
      - dev
      - UAT
      - main

jobs:
  build_aab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build AAB
        run: |
          echo "Job 1: Building AAB for branch '${{ github.event.ref }}'"

  shield_aab:
    runs-on: ubuntu-latest
    needs: build_aab
    if: github.event.ref == 'refs/heads/UAT' || github.event.ref == 'refs/heads/main'
    steps:
      - name: Shield AAB
        run: |
          echo "Job 2: Shielding AAB for branch '${{ github.event.ref }}'"

  deploy_aab:
    runs-on: ubuntu-latest
    needs: shield_aab
    if: github.event.ref == 'refs/heads/UAT' || github.event.ref == 'refs/heads/main'
    steps:
      - name: Deploy AAB
        run: |
          echo "Job 3: Deploying AAB for branch '${{ github.event.ref }}'"

  release_to_github:
    runs-on: ubuntu-latest
    needs: ${{ github.event.ref == 'refs/heads/dev' && 'build_aab' || (github.event.ref == 'refs/heads/UAT' && 'deploy_aab') || (github.event.ref == 'refs/heads/main' && 'deploy_aab') }}
    steps:
      - name: Release to GitHub
        run: |
          if [[ "${{ github.event.ref }}" == "refs/heads/dev" ]]; then
            echo "Job 4: Releasing Dev AAB..."
          else
            echo "Job 4: Releasing UAT/Main AAB..."
          fi
